.gitignore, Makefile
=> Build 2decomp as a standalone library

Makefile.compilers
Fix issue https://github.com/xcompact3d/2decomp-fft/issues/23
=> No automatic OpenMP by default

src/d2d_log.f90, src/decomp_2d.f90
Only rank 0 will print the environment variables.
=> Print environment variables in debug mode

src/decomp_2d.f90
This modification is proposed so that decomp_2d can use a specific given MPI communicator instead of MPI_COMM_WORLD
=> decomp_2d can use a MPI communicator different from MPI_COMM_WORLD

Makefile, README.md, examples/fft_test_c2c/Makefile, examples/fft_test_r2c/Makefile, examples/halo_test/Makefile, examples/io_test/Makefile, examples/test2d/Makefile, examples/timing/Makefile, src/d2d_log.f90, src/decomp_2d.f90, src/fft_common.f90, src/fft_common_3d.f90, src/fft_fftw3_f03.f90, src/profiler_caliper.f90, src/transpose_x_to_y.f90, src/transpose_y_to_x.f90, src/transpose_y_to_z.f90, src/transpose_z_to_y.f90
After loading the GNU compiler (11.2.0) and the OpenMPI library (4.1.0), Caliper (2.8.0) was compiled with :
```
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_INSTALL_PREFIX=xxxxxxxx/caliper/caliper_2.8.0 -DWITH_FORTRAN=yes -DWITH_MPI=yes -DBUILD_TESTING=yes ../
make -j
make test
make install
```
One test is failing but the draft seems to work.
=> Preliminary draft for the profiler

examples/fft_test_c2c/Makefile, examples/fft_test_r2c/Makefile, examples/fft_test_r2c/fft_test_r2c.f90, examples/halo_test/Makefile, examples/io_test/Makefile, examples/io_test/io_var_test.f90, examples/test2d/Makefile, examples/timing/Makefile
This prevents test building failing when stricter debug flags are enabled
=> Build test cases under strictrer (BUILD=debug/dev) flags

.github/workflows/Build.yml, Makefile
Also fix missing variable FC in Makefile.settings.
It would be nice to add the profiler caliper to the automatic build process, but it seems to lack a Debian / Ubuntu package
=> Add fftw3 to the automatic build process

.github/workflows/Build.yml
Check here for the corresponding build : https://github.com/mathrack/2decomp-fft/actions/runs/3133990107/jobs/5087990595
=> Add Caliper to the automatic build

src/fft_cufft.f90
Not tested yet.
See https://github.com/xcompact3d/2decomp-fft/issues/67
=> Add profiling to the cufft engine

.github/workflows/Build_all.yml
See the CI output here : https://github.com/mathrack/2decomp-fft/actions/runs/3306175860/jobs/5456871799
=> CI: add MKL FFT backend

src/decomp_2d.f90, src/decomp_2d_init_fin.f90
Have been able to build, but not test with nvhpc - when running the tests (on CPU) it complains about failing to load cuda library so I think dodgy environment.
I am able to build and run tests with aocc/flang which had shown the same failures as nvhpc in a simplified test code.
=> Potential fix for NVIDIA submodularisation

README.md, src/decomp_2d.f90, src/decomp_2d_init_fin.f90, src/log.f90
=> More options for the log output

README.md
=> Explain parallel configuration of examples

examples/Makefile, examples/init_test/.gitignore, examples/init_test/Makefile, examples/init_test/init_test.f90
Starting from a very simple case of testing that we can initialise the library and that the distribution of nodes is correct
=> Add initialisation test cases

src/io.f90, src/io_read_inflow.f90, src/io_read_var.inc, src/io_write_outflow.f90, src/io_write_var.inc
=> Update io for large cases

examples/init_test/bind.sh
Now everything seems ok also with the GPU just a bind file was missing.
=> Add binding for GPU run

README.md
=> Describe preprocessor variables in the README

Makefile, README.md, src/decomp_2d.f90, src/decomp_2d_constants.f90, src/decomp_2d_init_fin.f90, src/fft_common.f90, src/fft_cufft.f90, src/fft_fftw3.f90, src/fft_fftw3_f03.f90, src/fft_generic.f90, src/fft_mkl.f90, src/log.f90
=> Expose fft backend

examples/fft_physical_x/fft_c2c_x.f90, examples/fft_physical_x/fft_r2c_x.f90, examples/fft_physical_z/fft_c2c_z.f90, examples/fft_physical_z/fft_r2c_z.f90, examples/halo_test/halo_test.f90, examples/io_test/io_bench.f90, examples/io_test/io_plane_test.f90, examples/io_test/io_read.f90, examples/io_test/io_test.f90, examples/io_test/io_var_test.f90, src/decomp_2d.f90, src/fft_cufft.f90, src/fft_fftw3.f90, src/fft_fftw3_f03.f90, src/fft_generic.f90, src/fft_mkl.f90, src/log.f90
And update the examples to use the built-in allocator
=> Add a subroutine to close the listing IO unit

src/fft_common.f90, src/fft_generic.f90, src/fft_mkl.f90
The trick could apply to fftw3_f03 as well.
=> Fuse working arrays wk2_c2c and wk2_r2c

src/fft_common.f90, src/fft_mkl.f90
=> Fix MKL backend

src/decomp_2d.f90, src/transpose_x_to_y.f90, src/transpose_y_to_x.f90, src/transpose_y_to_z.f90, src/transpose_z_to_y.f90
Fix the issue with nccl Type. Tested in both single and double precision on 4 GPUs
=> Fix nccl type

src/decomp_2d_constants.f90, src/log.f90
=> Print major and minor version number

.github/workflows/Build.yml, .github/workflows/Build_all.yml, CMakeLists.txt, README.md
=> Deactivate testing as default option

README.md
Closing https://github.com/2decomp-fft/2decomp-fft/issues/179
=> Provide required / tested versions

src/CMakeLists.txt, src/decomp_2d.f90, src/transpose_x_to_y.f90, src/transpose_y_to_x.f90, src/transpose_y_to_z.f90, src/transpose_z_to_y.f90
For a synthetic view of the modification, please look at the first commit. The fprettify script has modified many lines.
=> Move transpose subroutines in dedicated submodules

src/CMakeLists.txt, src/decomp_2d.f90, src/transpose_x_to_y.f90, src/transpose_y_to_x.f90, src/transpose_y_to_z.f90, src/transpose_z_to_y.f90
Reverts 2decomp-fft/2decomp-fft#204
Broke NVHPC on CI, testing with IFX also not working.
However we should still aim for this approach.
=> Revert "Move transpose subroutines in dedicated submodules"

CMakeLists.txt, cmake/compilers/D2D_flags_gnu.cmake
=> Fix issue 214 adding the implicit procedure/interface only with generic

src/decomp_2d_constants.f90
This development branch is the future version 2.1 of the 2decomp library
=> Increment minor version number

src/io.f90
Code was commented out and should be removed
=> Remove old debugging code

INSTALL.md
=> Add instructions on vendor FFTW

examples/fft_physical_x/fft_c2c_x.f90, examples/fft_physical_x/fft_grid_x.f90, examples/fft_physical_x/fft_r2c_x.f90, examples/fft_physical_z/fft_c2c_z.f90, examples/fft_physical_z/fft_r2c_z.f90, examples/halo_test/halo_test.f90, examples/io_test/io_bench.f90, examples/io_test/io_test.f90, examples/test2d/timing2d_complex.f90, examples/test2d/timing2d_real.f90, src/factor.f90, src/io.f90
Update the timing of the example by giving results over an average and excluding the first iteration.
=> Timing examples

examples/README.md, examples/fft_physical_x/README, examples/fft_physical_z/README, examples/halo_test/README, examples/init_test/README, examples/io_test/README, examples/test2d/README
Update of the README for all example to reflect the new examples.
=> Update the README for the examples

examples/README.md, examples/fft_physical_x/README, examples/fft_physical_z/README, examples/halo_test/README, examples/init_test/README, examples/io_test/README, examples/test2d/README
Merge into dev the updated README for examples.
=> Merge main into dev

src/transpose_x_to_y.f90
Reverts 2decomp-fft/2decomp-fft#225
=> Revert "Minor refactoring in transpose subroutines"

examples/io_test/io_visu.f90
See https://github.com/2decomp-fft/2decomp-fft/pull/275#issuecomment-1790297873
=> Use decomp_2d_testing in io_visu.f90

.github/workflows/RunnerFastCI.yml, .github/workflows/RunnerFullCI.yml
Closing https://github.com/2decomp-fft/2decomp-fft/issues/198
=> CI + gpu : add a test for the cufft backend with inplace FFT

submissionjoss/paper.md
Add acknowledgement of eCSE funding
=> Update paper.md acknowledgements

submissionjoss/paper.md
=> Propose changes to paper.md

examples/fft_physical_x/fft_c2c_x.f90, examples/fft_physical_x/fft_grid_x.f90, examples/fft_physical_x/fft_r2c_x.f90, examples/fft_physical_z/fft_c2c_z.f90, examples/fft_physical_z/fft_r2c_z.f90, examples/test2d/test2d.f90, examples/test2d/timing2d_complex.f90, examples/test2d/timing2d_real.f90, src/decomp_2d_nccl.f90
Fix problem with NVHPC23 and NCCL. Issue was related that CUDA stream  needed to be synchronized. This apparently was not necessary until version NVHPC22.
When this merge is done I'll also merge into the dev branch.
=> Fix nvhpc23 nccl

src/decomp_2d_constants.f90
=> Backport replace profiler enum with integer parameters

src/decomp_2d.f90
The subroutine is working as expected and the last two lines are not needed.
=> Minor update in the distribute subroutine

.github/workflows/RunnerFastCI.yml, .github/workflows/RunnerFullCI.yml, INSTALL.md, cmake/D2D_MPI.cmake, cmake/compilers/D2D_flags_intel.cmake, examples/fft_physical_x/fft_c2c_x.f90, examples/fft_physical_x/fft_grid_x.f90, examples/fft_physical_x/fft_r2c_x.f90, examples/fft_physical_z/fft_c2c_z.f90, examples/fft_physical_z/fft_r2c_z.f90, examples/halo_test/halo_test.f90, src/fft_common.f90, src/halo_common.f90
Updated to the main to be compatible with Incompac3d main.
Main is the default branch that Incompact3d will use.
=> Update to be compatible with Incompact3D V5.0

.github/workflows/Build.yml, .github/workflows/Build_all.yml
* Update github action
* Update Build_all.yml
=> cherry-pick PR #325

src/fft_common.f90, src/fft_fftw3_f03.f90, src/io.f90, src/io_family.f90, src/io_object.f90
Remove all ierror=0 as argument of MPI_abort to activate MPI error on output and have CTest catching the error message and fail the test
=> Change ierror 

examples/io_test/io_test.f90
Revert modifications in io_test.f90 included in commit bada6371981176390e206bcc86e57963b454fbb8
=> Partial revert of commit bada6371981176390e206bcc86e57963b454fbb8

.github/workflows/RunnerFastCI.yml, .github/workflows/RunnerFullCI.yml, src/io.f90
=> Fix IO for reduced precision and 3D array in y / z pencil

.github/workflows/RunnerFastCI_double.yml, .github/workflows/RunnerFastCI_single.yml, .github/workflows/RunnerFullCI_INTEL_double.yml, .github/workflows/RunnerFullCI_INTEL_single.yml, examples/fft_multiple_grids/CMakeLists.txt
=> Update modules for Intel CI

.github/workflows/Build_all.yml
Intel have deprecated and removed ifort from the oneAPI distribution.
=> Replace ifort->ifx in CI
