2decomp-fft/2decomp-fft

Makefile
src/io.f90
src/io_read_inflow.f90
src/io_write_one.inc
src/io_write_outflow.f90

Mostly this is where a subroutine has an argument that is used by
ADIOS2 but not MPIIO or vice-versa.
Also discovered some unused variables

Fix compiler warnings in restore io branch

---

src/d2d_log.f90
src/decomp_2d.f90

When the DEBUG preprocessor variable is defined, the debug level can be changed
- From the external code, with a modification of the variable `decomp_debug` before calling `decomp_2d_init`
- Using the environment variable `DECOMP_2D_DEBUG`
If both strategies are employed, the environment variable is taken into account.
This PR can fix https://github.com/xcompact3d/2decomp-fft/issues/34

Allow finer control of the debug level

---

.gitignore
Makefile
README.md
examples/.gitignore
examples/Makefile
examples/fft_test_c2c/Makefile
examples/fft_test_c2c/fft_test_c2c.f90
examples/fft_test_r2c/Makefile
examples/fft_test_r2c/fft_test_r2c.f90
examples/halo_test/Makefile
examples/halo_test/halo_test.f90
examples/io_test/Makefile
examples/io_test/io_bench.f90
examples/io_test/io_plane_test.f90
examples/io_test/io_read.f90
examples/io_test/io_test.f90
examples/io_test/io_var_test.f90
examples/non_blocking/Makefile
examples/test2d/Makefile
examples/test2d/test2d.f90
examples/timing/Makefile
examples/timing/timing.f90
src/decomp_2d.f90

* Fix most of the examples. Compilation with gcc tested. The file fftdata is missing in fft_test_r2c
* The library can run even if the external code does not initialize nrank and nproc
* Examples can run with make check
* Update README.md
* Add a test to detect memory leaks
* Fix the example test2d
* Add a "memory" to Makefile execution
This allows building the library, then later testing without needing to specify the options again
* Update README to explain Makefile.settings
* Minor update for the fft_c2c example
* Rewrite halo test to run in memory (without IO)
Also change prow,pcol to 0 so it runs on arbitrary core count
* Abort halo test with non-zero error on failure
* Use decomp_2d_abort instead of MPI_abort in case of error
* Update Makefile for example/halo_test
* …

Fix examples

---

.github/workflows/Build.yml

This makes sure the code has been built with the strictest flags

Use BUILD=dev for default/fast build test on GH

---

Makefile

This prevents an error occurring when Makefile.settings does not exist (e.g. after make clean)

Add - infront of include

---

examples/fft_physical_z/Makefile

I'm assuming this is a clear-cut old piece of old code but thought worth checking with you @rfj82982

Delete old mem_leak target referencing timing in fft_physical_z

---

.gitignore
Makefile.compilers
examples/halo_test/halo_test.f90

Examples all passing locally using Intel + Intel MPI and gfortran (9.2) + openmpi (4.0.3) on 1 and 4 ranks

Fix/halo test  intel

---

src/decomp_2d_init_fin.f90

Currently, when checking the MPI error code, it is always checked against 0 and not against MPI_SUCCESS.
As far as I know, no MPI library is using a symbol MPI_SUCCESS /= 0. But just in case...

Make sure MPI_SUCCESS is 0

---

examples/Makefile
examples/fft_physical_x/Makefile
examples/fft_physical_x/fft_c2c_x.f90
examples/fft_physical_x/fft_r2c_x.f90
examples/fft_physical_z/Makefile
examples/fft_physical_z/fft_c2c_z.f90
examples/fft_physical_z/fft_r2c_z.f90

Split of the FFT examples into c2c and r2c. Tested on gnu/mpich, intel and nvhpc with all working. Only annoyance is the following warning from Intel
```
mpiifort  -fpp -std08 -O3 -mavx2 -march=core-avx2 -mtune=core-avx2 -module mod -Imod  -DDOUBLE_PREC -DVERSION=\"e8f2cc6\"  -c src/log.f90 -o obj/log.o
src/log.f90(85): warning #7416: Fortran 2008 does not allow this intrinsic procedure.   [COMPILER_VERSION]
write (io_unit, *) 'Compiled with ', compiler_version()
-----------------------------------------^
src/log.f90(86): warning #7416: Fortran 2008 does not allow this intrinsic procedure.   [COMPILER_OPTIONS]
write (io_unit, *) 'Compiler options : ', compiler_options()
----------------------------------------------^
mpiifort  -fpp -std08 -O3 -mavx2 -march=core-avx2 -mtune=core-avx2 …
```

Separate fft examples

---

Makefile
src/fft_mkl.f90

Add support for the overwrite preprocessor variable to the MKL FFT backend. The following performance was measured for a serial run on a 128x128x128 grid using the available examples : 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
</head>
<body>
  |   | x_c2c |   | x_r2c |   | z_c2c |   | z_r2c |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
time (sec) | master | 1.491651084 | 1.362318515 | 0.831514729 | 0.803822179 | 1.392889503 | 1.385034793 | 0.982878584 | 0.97138917
  | mkl_inplace | 1.331018543 | 1.25074677 | 0.665392137 | 0.643411227 | 1.30402926 | 1.275790235 | 0.887303425 | 0.895311678
  | mkl_inplace+overwrite | 0.805920441 | 0.767969895 | 0.427547905 | 0.442008324 | 0.800845234 | 0.765677335 | 0.668759219 | 0.635879963
  |   |   |   |   |   | …

MKL inplace

---

src/io.f90

The old style character*(*) is deprecated by newer compilers
Closes #116

Replace character*(*) -> character(len=*)

---

Makefile.compilers
README.md
examples/Makefile
examples/fft_physical_x/fft_c2c_x.f90
examples/fft_physical_x/fft_grid_x.f90
examples/fft_physical_x/fft_r2c_x.f90
examples/fft_physical_z/fft_c2c_z.f90
examples/fft_physical_z/fft_r2c_z.f90
examples/halo_test/Makefile
examples/halo_test/halo_test.f90
examples/io_test/io_plane_test.f90
examples/io_test/io_test.f90
examples/io_test/io_var_test.f90
examples/test2d/test2d.f90
src/fft_common.f90
src/fft_cufft.f90
src/fft_fftw3.f90
src/fft_fftw3_f03.f90
src/fft_log.f90
src/transpose_x_to_y.f90
src/transpose_y_to_x.f90
src/transpose_y_to_z.f90
src/transpose_z_to_y.f90

I have updated also the tests for 2decomp to adapt for the non memory managed case for GPU. The only missing is the halo since it requires some changes in the routines. 
I’ll also open a feature request to adapt the IO part of 2decomp. In the example of io for single plane only the write for aligned planes works  (i.e. X write for u1). The write plane has some transposes and for the manual memory management we need. This will give at least consistency that when doing IO we move the data to the host and we write from there. 
I would like to do the pull request to allow Wei and I to put properly the sin/cos transform.

Update fft (part 2)

---

src/log.f90

The file returned can contain the absolute path and can be relatively long.

Increase the size of the name of the log file

---

cmake/compilers/D2D_flags_cray.cmake

If module A uses MPI (for example) and module B uses modules A and MPI then this raises a warning. It seems safe to ignore so this silences it

Silence Cray warning about multiple module uses

---

examples/halo_test/halo_test.f90

The test originally used `div1` (global) as the reference data, this has been replaced to use data local to each test subroutine and the correct reference data (`div`, computed via transpose) used in the error check.
I'm not sure about the openACC data copy in/out for div1/2/3 though

Correct halo test

---

src/decomp_2d.f90
src/decomp_2d_init_fin.f90

When sharing real and complex transpose buffers, the memory used for transpose buffers is reduced by 33%
The proposed strategy can probably be also applied to transpose buffers used on the GPU

Use pointers to share real and complex CPU transpose buffers

---

.github/workflows/RunnerFastCI.yml
.github/workflows/RunnerFullCI.yml
examples/io_test/adios2_config.xml
examples/io_test/io_test.f90
src/io.f90

Restart-type I/O (multiple fields per file) wasn't being tested. Extended `io_test` to do file per field and single file, multiple field (i.e. checkpoint) writes and reads. This should be added to any branch used for JOSS

Test restarts

---

src/transpose_x_to_y.f90
src/transpose_y_to_x.f90
src/transpose_y_to_z.f90
src/transpose_z_to_y.f90

Current transpose operations are not always profiled when p_row or p_col is equal to one.

Profile transpose operations when no MPI communication is performed

---

src/CMakeLists.txt
src/decomp_2d.f90
src/decomp_2d_constants.f90
src/decomp_2d_init_fin.f90
src/fft_cufft.f90
src/fft_fftw3.f90
src/fft_fftw3_f03.f90
src/fft_generic.f90
src/fft_mkl.f90
src/io.f90
src/log.f90
src/profiler_caliper.f90
src/profiler_none.f90

Most of the directives are kept to avoid conflicts with pending PR targeting the FFT backends, IO refactoring and transpose subroutines.

Add a profiler none dummy module allowing removal of the PROFILER preprocessor directives.

---

CHANGELOG.md
src/decomp_2d.f90
src/log.f90

The external code should define them directly.
The external code should also adopt a sharper naming convention.

Remove unused decomp_info objects ph*

---

CHANGELOG.md
src/io_adios_none.f90
src/io_mpi.f90

The external code can avoid preprocessor directives (`#ifdef ADIOS2`) and perform IO with a simpler structure : 
```
if (decomp_2d_with_adios2) call decomp_2d_register_var("io.dat", 1, real_type)
...
if (decomp_2d_with_adios2) then
call decomp_2d_adios_write_var(io, u1, 'io.dat')
call io%end_close
else
call decomp_2d_write_one(1, u1, 'io.dat', opt_dirname="./")
end if
```

Extend the dummy ADIOS2 interface to include most of the objects / functions / subroutines available in the ADIOS2 module

---

src/transpose_x_to_y.f90
src/transpose_y_to_x.f90
src/transpose_y_to_z.f90
src/transpose_z_to_y.f90

Latest change to memplit/merge have introduced a new starting index for OpenMP vectorisation. This should have propagated also in the cudaMemCpy2D to rearrange the arrays.

Fix index for cudaMemCpy2D for Mem split/merge

---

src/decomp_2d_mpi.f90

2decomp should not call MPI_COMM_FREE on the provided communicator
Minor modification, no update of the changelog.

Set decomp_2d_comm to MPI_COMM_NULL when the module is finalized

---

src/transpose_y_to_z.f90
src/transpose_z_to_y.f90

Remove the openACC directives for CUDA aware MPI call and use only device arrays for all MPI_ALLTOALL(V).  
The more elegant version with directives was not stable and sometimes was leading to errors.

Remove openACC data clause from MPI call

---

cmake/compilers/D2D_flags_cray.cmake
examples/cmake/D2D_CREATE_TEST.cmake
src/decomp_2d_constants.f90

Newer Cray compilers (CCE 16+?) require that OpenMP is linked explicitly, whereas older ones did not. CMake does not add `-h omp` to the link line, see https://gitlab.kitware.com/cmake/cmake/-/issues/26129

Fix OpenMP compilation with new Cray compilers
